# This is a basic workflow to help you get started with Actions

name: Automatic Release

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-labels:
    # if: ${{ (github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.match-label.outputs.match }}
    steps:
      - uses: actions/checkout@v3
      - id: match-label
        shell: bash
        run: |
          .github/workflows/get-label.sh -n 'major, minor, patch' -l '${{ join(github.event.issue.labels.*.name, ', ') }}'
          echo "::set-output name=match::$(cat match.txt)"

  semver-version:
    needs:
      - get-labels
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: zwaldowski/semver-release-action@v2
        id: version
        with:
          bump: ${{ needs.get-labels.outputs.labels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

#  build:
#    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'site')) }}
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - uses: actions/checkout@v3
#
#      - users
#
#      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run: echo Hello, world!
#
#      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
