# This is a basic workflow to help you get started with Actions

name: Automatic Release

# Controls when the workflow will run
on:
  pull_request:
    branches: [main]
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  contains-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'patch, minor, major'